import type { RouteRecordRaw } from 'vue-router'

const authRoutes: RouteRecordRaw[] = [
  'login',
  'register',
  'forgot-password',
  'reset-password',
  'verify-email',
  'two-factor',
  'lock-screen',
].map((slug) => ({
  path: `/auth/${slug}`,
  name: `auth.${slug}`,
  component: () => import('@/pages/auth/AuthSamplePage.vue'),
  meta: {
    title: slug.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join(' '),
    layout: 'auth',
    breadcrumb: ['Template Pages', 'Authentication'],
  },
}))

const errorRoutes: RouteRecordRaw[] = ['403', '404', '500'].map((code) => ({
  path: `/errors/${code}`,
  name: `errors.${code}`,
  component: () => import('@/pages/errors/ErrorPage.vue'),
  meta: {
    title: `${code} Error`,
    layout: 'blank',
    breadcrumb: ['Template Pages', 'Error Pages'],
  },
}))

export const routes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'landing',
    component: () => import('@/pages/public/LandingPage.vue'),
    meta: {
      title: 'Nata Admin — Vue Tailwind Admin Template',
      layout: 'public',
    },
  },
  {
    path: '/docs',
    name: 'docs',
    component: () => import('@/pages/public/DocsPage.vue'),
    meta: {
      title: 'Documentation | Nata Admin',
      layout: 'public',
    },
  },
  {
    path: '/dashboard',
    name: 'dashboard.overview',
    component: () => import('@/pages/dashboard/DashboardOverviewPage.vue'),
    meta: {
      title: 'Dashboard Overview',
      layout: 'admin',
      breadcrumb: ['Dashboard', 'Overview'],
    },
  },
  {
    path: '/dashboard/analytics',
    name: 'dashboard.analytics',
    component: () => import('@/pages/dashboard/AnalyticsDashboardPage.vue'),
    meta: {
      title: 'Analytics Dashboard',
      layout: 'admin',
      breadcrumb: ['Dashboard', 'Analytics'],
    },
  },
  {
    path: '/dashboard/sales',
    name: 'dashboard.sales',
    component: () => import('@/pages/dashboard/SalesDashboardPage.vue'),
    meta: {
      title: 'Sales Dashboard',
      layout: 'admin',
      breadcrumb: ['Dashboard', 'Sales'],
    },
  },
  {
    path: '/apps/email',
    name: 'apps.email',
    component: () => import('@/pages/apps/EmailPage.vue'),
    meta: {
      title: 'Email',
      layout: 'admin',
      breadcrumb: ['Apps', 'Email'],
    },
  },
  {
    path: '/apps/chat',
    name: 'apps.chat',
    component: () => import('@/pages/apps/ChatPage.vue'),
    meta: {
      title: 'Chat',
      layout: 'admin',
      breadcrumb: ['Apps', 'Chat'],
    },
  },
  {
    path: '/apps/calendar',
    name: 'apps.calendar',
    component: () => import('@/pages/apps/CalendarPage.vue'),
    meta: {
      title: 'Calendar',
      layout: 'admin',
      breadcrumb: ['Apps', 'Calendar'],
    },
  },
  {
    path: '/apps/kanban',
    name: 'apps.kanban',
    component: () => import('@/pages/apps/KanbanPage.vue'),
    meta: {
      title: 'Kanban',
      layout: 'admin',
      breadcrumb: ['Apps', 'Kanban'],
    },
  },
  {
    path: '/apps/tasks',
    name: 'apps.tasks',
    component: () => import('@/pages/apps/TasksPage.vue'),
    meta: {
      title: 'Tasks',
      layout: 'admin',
      breadcrumb: ['Apps', 'Tasks'],
    },
  },
  {
    path: '/apps/file-manager',
    name: 'apps.file-manager',
    component: () => import('@/pages/apps/FileManagerPage.vue'),
    meta: {
      title: 'File Manager',
      layout: 'admin',
      breadcrumb: ['Apps', 'File Manager'],
    },
  },
  {
    path: '/apps/notes',
    name: 'apps.notes',
    component: () => import('@/pages/apps/NotesPage.vue'),
    meta: {
      title: 'Notes',
      layout: 'admin',
      breadcrumb: ['Apps', 'Notes'],
    },
  },
  {
    path: '/management/users',
    name: 'management.users',
    component: () => import('@/pages/management/UsersListPage.vue'),
    meta: { title: 'Users', layout: 'admin', breadcrumb: ['Management', 'Users'] },
  },
  {
    path: '/management/users/:id',
    name: 'management.users.detail',
    component: () => import('@/pages/management/UserDetailPage.vue'),
    meta: { title: 'User Detail', layout: 'admin', breadcrumb: ['Management', 'Users', 'Detail'] },
  },
  {
    path: '/management/roles',
    name: 'management.roles',
    component: () => import('@/pages/management/RolesPermissionsPage.vue'),
    meta: { title: 'Roles & Permissions', layout: 'admin', breadcrumb: ['Management', 'Roles & Permissions'] },
  },
  {
    path: '/management/customers',
    name: 'management.customers',
    component: () => import('@/pages/management/CustomersListPage.vue'),
    meta: { title: 'Customers', layout: 'admin', breadcrumb: ['Management', 'Customers'] },
  },
  {
    path: '/management/customers/:id',
    name: 'management.customers.detail',
    component: () => import('@/pages/management/CustomerDetailPage.vue'),
    meta: { title: 'Customer Detail', layout: 'admin', breadcrumb: ['Management', 'Customers', 'Detail'] },
  },
  {
    path: '/management/products',
    name: 'management.products',
    component: () => import('@/pages/management/ProductsListPage.vue'),
    meta: { title: 'Products', layout: 'admin', breadcrumb: ['Products', 'Product List'] },
  },
  {
    path: '/management/products/:id/edit',
    name: 'management.products.edit',
    component: () => import('@/pages/management/ProductEditPage.vue'),
    meta: { title: 'Edit Product', layout: 'admin', breadcrumb: ['Products', 'Edit Product'] },
  },
  {
    path: '/management/products/:id',
    name: 'management.products.detail',
    component: () => import('@/pages/management/ProductDetailPage.vue'),
    meta: { title: 'Product Detail', layout: 'admin', breadcrumb: ['Products', 'Product Detail'] },
  },
  {
    path: '/management/product-categories',
    name: 'management.product-categories',
    component: () => import('@/pages/management/ProductCategoriesPage.vue'),
    meta: { title: 'Product Categories', layout: 'admin', breadcrumb: ['Products', 'Product Categories'] },
  },
  {
    path: '/management/orders',
    name: 'management.orders',
    component: () => import('@/pages/management/OrdersListPage.vue'),
    meta: { title: 'Orders', layout: 'admin', breadcrumb: ['Management', 'Orders'] },
  },
  {
    path: '/management/orders/:id',
    name: 'management.orders.detail',
    component: () => import('@/pages/management/OrderDetailPage.vue'),
    meta: { title: 'Order Detail', layout: 'admin', breadcrumb: ['Management', 'Orders', 'Detail'] },
  },
  {
    path: '/finance/invoices',
    name: 'finance.invoices',
    component: () => import('@/pages/finance/InvoicesListPage.vue'),
    meta: { title: 'Invoices', layout: 'admin', breadcrumb: ['Finance', 'Invoices'] },
  },
  {
    path: '/finance/invoices/create',
    name: 'finance.invoices.create',
    component: () => import('@/pages/finance/CreateInvoicePage.vue'),
    meta: { title: 'Create Invoice', layout: 'admin', breadcrumb: ['Finance', 'Invoices', 'Create'] },
  },
  {
    path: '/finance/invoices/:id',
    name: 'finance.invoices.detail',
    component: () => import('@/pages/finance/InvoiceDetailPage.vue'),
    meta: { title: 'Invoice Detail', layout: 'admin', breadcrumb: ['Finance', 'Invoices', 'Detail'] },
  },
  {
    path: '/finance/transactions',
    name: 'finance.transactions',
    component: () => import('@/pages/finance/TransactionsListPage.vue'),
    meta: { title: 'Transactions', layout: 'admin', breadcrumb: ['Finance', 'Transactions'] },
  },
  {
    path: '/finance/payments',
    name: 'finance.payments',
    component: () => import('@/pages/finance/PaymentsPage.vue'),
    meta: { title: 'Payments', layout: 'admin', breadcrumb: ['Finance', 'Payments'] },
  },
  {
    path: '/finance/pricing-plans',
    name: 'finance.pricing-plans',
    component: () => import('@/pages/finance/PricingPlansPage.vue'),
    meta: { title: 'Pricing Plans', layout: 'admin', breadcrumb: ['Finance', 'Pricing Plans'] },
  },
  {
    path: '/finance/billing-history',
    name: 'finance.billing-history',
    component: () => import('@/pages/finance/BillingHistoryPage.vue'),
    meta: { title: 'Billing History', layout: 'admin', breadcrumb: ['Finance', 'Billing History'] },
  },
  {
    path: '/content/pages',
    name: 'content.pages',
    component: () => import('@/pages/content/PagesListPage.vue'),
    meta: { title: 'Pages', layout: 'admin', breadcrumb: ['Content', 'Pages'] },
  },
  {
    path: '/content/pages/editor',
    name: 'content.pages.editor',
    component: () => import('@/pages/content/PageEditorPage.vue'),
    meta: { title: 'Page Editor', layout: 'admin', breadcrumb: ['Content', 'Pages', 'Editor'] },
  },
  {
    path: '/content/digital-product-editor',
    name: 'content.digital-product-editor',
    component: () => import('@/pages/content/DigitalProductPageEditorPage.vue'),
    meta: { title: 'Digital Product Editor', layout: 'admin', breadcrumb: ['Products', 'Digital Product Editor'] },
  },
  {
    path: '/content/product-source',
    name: 'content.product-source',
    component: () => import('@/pages/content/ProductSourcePage.vue'),
    meta: { title: 'Product Source', layout: 'admin', breadcrumb: ['Products', 'Product Source'] },
  },
  {
    path: '/content/media',
    name: 'content.media',
    component: () => import('@/pages/content/MediaLibraryPage.vue'),
    meta: { title: 'Media Library', layout: 'admin', breadcrumb: ['Content', 'Media'] },
  },
  {
    path: '/content/faq',
    name: 'content.faq',
    component: () => import('@/pages/content/FaqPage.vue'),
    meta: { title: 'FAQ', layout: 'admin', breadcrumb: ['Content', 'FAQ'] },
  },
  {
    path: '/content/help-center',
    name: 'content.help-center',
    component: () => import('@/pages/content/HelpCenterPage.vue'),
    meta: { title: 'Help Center', layout: 'admin', breadcrumb: ['Content', 'Help Center'] },
  },
  {
    path: '/reports/sales',
    name: 'reports.sales',
    component: () => import('@/pages/reports/SalesReportPage.vue'),
    meta: { title: 'Sales Report', layout: 'admin', breadcrumb: ['Reports', 'Sales Report'] },
  },
  {
    path: '/reports/user-activity',
    name: 'reports.user-activity',
    component: () => import('@/pages/reports/UserActivityPage.vue'),
    meta: { title: 'User Activity', layout: 'admin', breadcrumb: ['Reports', 'User Activity'] },
  },
  {
    path: '/reports/audit-logs',
    name: 'reports.audit-logs',
    component: () => import('@/pages/reports/AuditLogsPage.vue'),
    meta: { title: 'Audit Logs', layout: 'admin', breadcrumb: ['Reports', 'Audit Logs'] },
  },
  {
    path: '/reports/export-center',
    name: 'reports.export-center',
    component: () => import('@/pages/reports/ExportCenterPage.vue'),
    meta: { title: 'Export Center', layout: 'admin', breadcrumb: ['Reports', 'Export Center'] },
  },
  {
    path: '/system/general-settings',
    name: 'system.general-settings',
    component: () => import('@/pages/system/GeneralSettingsPage.vue'),
    meta: { title: 'General Settings', layout: 'admin', breadcrumb: ['System', 'General Settings'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/profile-settings',
    name: 'system.profile-settings',
    component: () => import('@/pages/system/ProfileSettingsPage.vue'),
    meta: { title: 'Profile Settings', layout: 'admin', breadcrumb: ['System', 'Profile Settings'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/company-settings',
    name: 'system.company-settings',
    component: () => import('@/pages/system/CompanySettingsPage.vue'),
    meta: { title: 'Company Settings', layout: 'admin', breadcrumb: ['System', 'Company Settings'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/notification-settings',
    name: 'system.notification-settings',
    component: () => import('@/pages/system/NotificationSettingsPage.vue'),
    meta: { title: 'Notification Settings', layout: 'admin', breadcrumb: ['System', 'Notification Settings'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/security-settings',
    name: 'system.security-settings',
    component: () => import('@/pages/system/SecuritySettingsPage.vue'),
    meta: { title: 'Security Settings', layout: 'admin', breadcrumb: ['System', 'Security Settings'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/api-keys',
    name: 'system.api-keys',
    component: () => import('@/pages/system/ApiKeysPage.vue'),
    meta: { title: 'API Keys', layout: 'admin', breadcrumb: ['System', 'API Keys'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/integrations',
    name: 'system.integrations',
    component: () => import('@/pages/system/IntegrationsPage.vue'),
    meta: { title: 'Integrations', layout: 'admin', breadcrumb: ['System', 'Integrations'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/webhooks',
    name: 'system.webhooks',
    component: () => import('@/pages/system/WebhooksPage.vue'),
    meta: { title: 'Webhooks', layout: 'admin', breadcrumb: ['System', 'Webhooks'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/system/appearance',
    name: 'system.appearance',
    component: () => import('@/pages/system/AppearancePage.vue'),
    meta: { title: 'Appearance', layout: 'admin', breadcrumb: ['System', 'Appearance'], requiresAuth: true, permission: 'settings.view' },
  },
  {
    path: '/utility/maintenance',
    name: 'utility.maintenance',
    component: () => import('@/pages/template-pages/MaintenancePage.vue'),
    meta: { title: 'Maintenance', layout: 'blank', breadcrumb: ['Template Pages', 'Utility Pages'] },
  },
  {
    path: '/utility/coming-soon',
    name: 'utility.coming-soon',
    component: () => import('@/pages/template-pages/ComingSoonPage.vue'),
    meta: { title: 'Coming Soon', layout: 'blank', breadcrumb: ['Template Pages', 'Utility Pages'] },
  },
  {
    path: '/profile',
    name: 'profile',
    component: () => import('@/pages/template-pages/ProfilePage.vue'),
    meta: { title: 'Profile', layout: 'admin', breadcrumb: ['Template Pages', 'Profile'] },
  },
  {
    path: '/account',
    name: 'account',
    component: () => import('@/pages/template-pages/AccountPage.vue'),
    meta: { title: 'Account', layout: 'admin', breadcrumb: ['Template Pages', 'Account'] },
  },
  {
    path: '/activity',
    name: 'activity',
    component: () => import('@/pages/template-pages/ActivityPage.vue'),
    meta: { title: 'Activity', layout: 'admin', breadcrumb: ['Template Pages', 'Activity'] },
  },
  {
    path: '/timeline',
    name: 'timeline',
    component: () => import('@/pages/template-pages/TimelinePage.vue'),
    meta: { title: 'Timeline', layout: 'admin', breadcrumb: ['Template Pages', 'Timeline'] },
  },
  {
    path: '/search-results',
    name: 'search-results',
    component: () => import('@/pages/template-pages/SearchResultsPage.vue'),
    meta: { title: 'Search Results', layout: 'admin', breadcrumb: ['Template Pages', 'Search Results'] },
  },
  {
    path: '/empty-state',
    name: 'empty-state',
    component: () => import('@/pages/template-pages/EmptyStatePage.vue'),
    meta: { title: 'Empty State', layout: 'blank', breadcrumb: ['Template Pages', 'Empty State'] },
  },
  {
    path: '/components/colors',
    name: 'components.colors',
    component: () => import('@/pages/components/ColorsPage.vue'),
    meta: { title: 'Colors', layout: 'admin', breadcrumb: ['Components Preview', 'Colors'] },
  },
  {
    path: '/components/typography',
    name: 'components.typography',
    component: () => import('@/pages/components/TypographyPage.vue'),
    meta: { title: 'Typography', layout: 'admin', breadcrumb: ['Components Preview', 'Typography'] },
  },
  {
    path: '/components/buttons',
    name: 'components.buttons',
    component: () => import('@/pages/components/ButtonsPage.vue'),
    meta: { title: 'Buttons', layout: 'admin', breadcrumb: ['Components Preview', 'Buttons'] },
  },
  {
    path: '/components/cards',
    name: 'components.cards',
    component: () => import('@/pages/components/CardsPage.vue'),
    meta: { title: 'Cards', layout: 'admin', breadcrumb: ['Components Preview', 'Cards'] },
  },
  {
    path: '/components/badges',
    name: 'components.badges',
    component: () => import('@/pages/components/BadgesPage.vue'),
    meta: { title: 'Badges', layout: 'admin', breadcrumb: ['Components Preview', 'Badges'] },
  },
  {
    path: '/components/alerts',
    name: 'components.alerts',
    component: () => import('@/pages/components/AlertsPage.vue'),
    meta: { title: 'Alerts', layout: 'admin', breadcrumb: ['Components Preview', 'Alerts'] },
  },
  {
    path: '/components/forms',
    name: 'components.forms',
    component: () => import('@/pages/components/FormsPage.vue'),
    meta: { title: 'Forms', layout: 'admin', breadcrumb: ['Components Preview', 'Forms'] },
  },
  {
    path: '/components/tables',
    name: 'components.tables',
    component: () => import('@/pages/components/TablesPage.vue'),
    meta: { title: 'Tables', layout: 'admin', breadcrumb: ['Components Preview', 'Tables'] },
  },
  {
    path: '/components/charts',
    name: 'components.charts',
    component: () => import('@/pages/components/ChartsPage.vue'),
    meta: { title: 'Charts', layout: 'admin', breadcrumb: ['Components Preview', 'Charts'] },
  },
  {
    path: '/components/modals',
    name: 'components.modals',
    component: () => import('@/pages/components/ModalsPage.vue'),
    meta: { title: 'Modals', layout: 'admin', breadcrumb: ['Components Preview', 'Modals'] },
  },
  {
    path: '/components/tabs',
    name: 'components.tabs',
    component: () => import('@/pages/components/TabsPage.vue'),
    meta: { title: 'Tabs', layout: 'admin', breadcrumb: ['Components Preview', 'Tabs'] },
  },
  {
    path: '/components/dropdowns',
    name: 'components.dropdowns',
    component: () => import('@/pages/components/DropdownsPage.vue'),
    meta: { title: 'Dropdowns', layout: 'admin', breadcrumb: ['Components Preview', 'Dropdowns'] },
  },
  {
    path: '/components/empty-states',
    name: 'components.empty-states',
    component: () => import('@/pages/components/EmptyStatesPage.vue'),
    meta: { title: 'Empty States', layout: 'admin', breadcrumb: ['Components Preview', 'Empty States'] },
  },
  {
    path: '/components/icons',
    name: 'components.icons',
    component: () => import('@/pages/components/IconsPage.vue'),
    meta: { title: 'Icons', layout: 'admin', breadcrumb: ['Components Preview', 'Icons'] },
  },
  ...authRoutes,
  ...errorRoutes,
  {
    path: '/:pathMatch(.*)*',
    redirect: '/errors/404',
  },
]
